---
# See https://github.com/jvautier/project-cli
fullname: jvautier/summon-provider-ssm
description: Summon provider for aws ssm
tags:
  - summon
  - ssm
  - aws
github:
  has_issues: true
  has_projects: false
  has_wiki: false
